'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
'
Namespace evware.update
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="UpdateBinding", [Namespace]:="http://www.evware.com/updatephp")>  _
    Partial Public Class Update
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CheckForUpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.MyCore.My.MySettings.Default.MyCore_evware_update_Update
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CheckForUpdateCompleted As CheckForUpdateCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.evware.com/update.php/CheckForUpdate", RequestNamespace:="http://www.evware.com/updatephp", ResponseNamespace:="http://www.evware.com/updatephp")>  _
        Public Function CheckForUpdate(ByVal machine_key As String) As <System.Xml.Serialization.SoapElementAttribute("return")> VersionInfo
            Dim results() As Object = Me.Invoke("CheckForUpdate", New Object() {machine_key})
            Return CType(results(0),VersionInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CheckForUpdateAsync(ByVal machine_key As String)
            Me.CheckForUpdateAsync(machine_key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CheckForUpdateAsync(ByVal machine_key As String, ByVal userState As Object)
            If (Me.CheckForUpdateOperationCompleted Is Nothing) Then
                Me.CheckForUpdateOperationCompleted = AddressOf Me.OnCheckForUpdateOperationCompleted
            End If
            Me.InvokeAsync("CheckForUpdate", New Object() {machine_key}, Me.CheckForUpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnCheckForUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.CheckForUpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CheckForUpdateCompleted(Me, New CheckForUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.evware.com/updatephp")>  _
    Partial Public Class VersionInfo
        
        Private dateField As String
        
        Private titleField As String
        
        Private descriptionField As String
        
        Private priorityField As String
        
        Private urlField As String
        
        Private contract_currentField As Boolean
        
        Private auto_updateField As Boolean
        
        '''<remarks/>
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")>  _
        Public Property priority() As String
            Get
                Return Me.priorityField
            End Get
            Set
                Me.priorityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contract_current() As Boolean
            Get
                Return Me.contract_currentField
            End Get
            Set
                Me.contract_currentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property auto_update() As Boolean
            Get
                Return Me.auto_updateField
            End Get
            Set
                Me.auto_updateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")>  _
    Public Delegate Sub CheckForUpdateCompletedEventHandler(ByVal sender As Object, ByVal e As CheckForUpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CheckForUpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As VersionInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),VersionInfo)
            End Get
        End Property
    End Class
End Namespace
